[package]
name = "shell_texturing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-macroquad = { git = "https://github.com/gre-v-el/egui-macroquad-updated.git" }
obj = "0.10.2"
